language: java
jdk: oraclejdk8
sudo: false
 
cache:
  directories:
    - ~/.m2
before_cache:
  - rm -rf ~/.m2/repository/org/universAAL

branches: 
 only:
 - master

env:
  global:
    secure: "i4SmBuoyoLeXeoBDFzsqVEegQyqM88avOXsyE/hEngqct0FGWtZoyaWBCF8DcmQAGyw7ak8VPhIEJws/aa36zIq2GDF3+s0LfksO8YywEuxFQKV8fAPr/U9umC+Kc0ubNAzQOs60bsJJXeMwtqQa5pd/fh4dojCTSiYE2dmcotQ="

addons:
  apt:
    packages:
      - graphviz

before_install:
 - cd ctxt.pom
 - (curl -s https://raw.githubusercontent.com/universAAL/platform/master/uAAL.pom/src/scripts/settings.xml) > settings.xml
 - cp settings.xml $HOME/.m2/settings.xml
 - (curl -s https://raw.githubusercontent.com/universAAL/platform/master/uAAL.pom/src/scripts/ci.sh) > ci.sh
 - chmod +x ci.sh
 - export MY_REPO="context"

install:
 -

before_script:
 - cat /etc/mavenrc || true
 - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc

script:
 - ./ci.sh script

after_success:
 - ./ci.sh success

notifications:
  email: false
